const destination = [
    {
      id: 1,
      name: "Colombo",
      image: "https://media.onyx-hospitality.com/-/media/project/amari/common/property/colombo/hotel_4share.jpg?rev=9a89a2a3078c4869ad8a5da2b2ec301c",
      description: "The vibrant capital of Sri Lanka, blending modern urban life with historical landmarks and cultural diversity.",
      rating: 4.8,
      price: 8000,
      category: "City",
      region: "Western Province",
      activities: ["Culture", "Shopping", "Nature", "History"]
    },
    {
      id: 2,
      name: "Kandy",
      image: "https://whc.unesco.org/uploads/thumbs/site_0450_0020-1200-630-20151105154018.jpg",
      description: "The cultural capital of Sri Lanka, home to the Temple of the Sacred Tooth Relic and picturesque landscapes.",
      rating: 4.8,
      price: 10000,
      category: "City",
      region: "Central Province",
      activities: ["Culture", "Nature", "History"]
    },
    {
      id: 3,
      name: "Galle",
      image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/176690402.jpg?k=387c7eca667c9bb0106eb68e87e102f1403603e1647498d3a935ee2180b31c77&o=&hp=1",
      description: "A historic coastal city with Dutch colonial architecture and beautiful beaches.",
      rating: 4.7,
      price: 12000,
      category: "City",
      region: "Southern Province",
      activities: ["History", "Beach", "Nature"]
    },
    {
      id: 4,
      name: "Nuwara Eliya",
      image: "https://destinationlesstravel.com/wp-content/uploads/2020/04/Depositphotos_66721069_XL.jpg",
      description: "A charming hill station nicknamed 'Little England,' known for tea plantations and colonial-era buildings.",
      rating: 4.6,
      price: 9000,
      category: "City",
      region: "Central Province",
      activities: ["Nature", "History", "Hiking"]
    },
    {
      id: 5,
      name: "Anuradhapura",
      image: "https://media-cdn.tripadvisor.com/media/photo-s/18/c6/dc/f2/anuradhapura-sri-lanka.jpg",
      description: "An ancient city and UNESCO World Heritage Site famous for Buddhist stupas and historic ruins.",
      rating: 4.8,
      price: 7000,
      category: "City",
      region: "North Central Province",
      activities: ["History", "Culture"]
    },
    {
      id: 6,
      name: "Sigiriya",
      image: "https://i0.wp.com/geologyscience.com/wp-content/uploads/2023/08/Sigiriya.webp?resize=1024%2C683&ssl=1",
      description: "Home to the iconic Lion Rock, a UNESCO World Heritage site with stunning frescoes and gardens.",
      rating: 4.9,
      price: 8500,
      category: "Historic Site",
      region: "Central Province",
      activities: ["History", "Nature", "Hiking"]
    },
    {
      id: 7,
      name: "Ella",
      image: "https://destinationlesstravel.com/wp-content/uploads/2019/05/DSC_9600-1-1024x684-1024x684.jpg",
      description: "A small hill town known for its scenic beauty, hiking trails, and waterfalls.",
      rating: 4.8,
      price: 9500,
      category: "Hill Station",
      region: "Uva Province",
      activities: ["Hiking", "Nature"]
    },
    {
      id: 8,
      name: "Jaffna",
      image: "https://www.reddottours.com/uploads/Blogs/a-tourists-guide-to-jaffna-sri-lanka/a-tourists-guide-to-jaffna-sri-lanka-header.jpg",
      description: "A cultural and historical hub in the Northern Province, rich in Tamil heritage and coastal charm.",
      rating: 4.4,
      price: 6500,
      category: "City",
      region: "Northern Province",
      activities: ["Culture", "History", "Nature"]
    },
    {
      id: 9,
      name: "Bentota",
      image: "https://deyotours.com/wp-content/uploads/2022/09/Bentota-view-from-upper.jpg",
      description: "A beachside destination perfect for relaxation, water sports, and luxury resorts.",
      rating: 4.6,
      price: 11000,
      category: "Beach",
      region: "Southern Province",
      activities: ["Beach", "Water Sports", "Nature"]
    },
    {
      id: 10,
      name: "Hikkaduwa",
      image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/83048674.jpg?k=99a331e67c4bd9f6dd7ba7682e709bfcd2a0661cb726a825691f4d80e3eda15d&o=&hp=1",
      description: "A vibrant coastal town known for coral reefs, snorkeling, and nightlife.",
      rating: 4.7,
      price: 9000,
      category: "Beach",
      region: "Southern Province",
      activities: ["Beach", "Water Sports"]
    },
    {
      id: 11,
      name: "Polonnaruwa",
      image: "https://www.bluelankatours.com/wp-content/uploads/2023/08/lankathilake.jpg",
      description: "A historic city featuring well-preserved ruins of palaces, temples, and sculptures.",
      rating: 4.8,
      price: 6000,
      category: "Historic Site",
      region: "North Central Province",
      activities: ["History", "Culture"]
    },
    {
      id: 12,
      name: "Mirissa",
      image: "https://somethingoffreedom.com/wp-content/uploads/2018/01/Palm-tree-grove-Mirissa.jpg",
      description: "A coastal paradise famous for its pristine beaches and whale watching tours.",
      rating: 4.9,
      price: 10000,
      category: "Beach",
      region: "Southern Province",
      activities: ["Beach", "Water Sports"]
    },
    {
      id: 13,
      name: "Trincomalee",
      image: "https://www.ugaescapes.com/junglebeach/wp-content/uploads/sites/5/2022/08/attraction-800-2.jpg",
      description: "A beautiful port city with stunning beaches, a natural harbor, and historic temples.",
      rating: 4.7,
      price: 8500,
      category: "Beach",
      region: "Eastern Province",
      activities: ["Beach", "Water Sports"]
    },
    {
      id: 14,
      name: "Arugam Bay",
      image: "https://mahaweli.lk/wp-content/uploads/2022/11/Arugam-Bay-Sri-Lanka.jpg",
      description: "A world-renowned surfing destination with a laid-back atmosphere.",
      rating: 4.8,
      price: 7500,
      category: "Beach",
      region: "Eastern Province",
      activities: ["Beach", "Water Sports"]
    },
    {
      id: 15,
      name: "Yala National Park",
      image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/09/f2/0f/25.jpg",
      description: "A wildlife haven famous for leopards, elephants, and other exotic animals.",
      rating: 4.9,
      price: 15000,
      category: "Nature",
      region: "Southern Province",
      activities: ["Nature"]
    },
    {
        id: 16,
        name: "Udawalawe National Park",
        image: "https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1200,h_630/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/asrudlfpyz1zebgd4cnf/Udawalawe%20National%20Park%20Private%20Safari%20Tour%20from%20Bentota.jpg",
        description: "A stunning wildlife park known for its large herds of elephants and diverse bird species.",
        rating: 4.8,
        price: 10000,
        category: "Nature",
        region: "Southern Province",
        activities: ["All", "Nature"]
      },
      {
        id: 17,
        name: "Dambulla",
        image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/463272382.jpg?k=febff53b4517d33d98422cb2abc512bca2fcb9cd6dc2ebc779bf5b850d80d60e&o=&hp=1",
        description: "A UNESCO World Heritage site featuring the largest and best-preserved cave temple complex in Sri Lanka.",
        rating: 4.7,
        price: 6000,
        category: "Historic Site",
        region: "Central Province",
        activities: ["All", "Culture", "History", "Hiking"]
      },
      {
        id: 18,
        name: "Kalpitiya",
        image: "https://www.srilankainstyle.com/storage/app/media/Locations/Kalpitiya-2.jpg",
        description: "A serene coastal town known for kite surfing, dolphin watching, and its unique lagoon ecosystem.",
        rating: 4.6,
        price: 8000,
        category: "Beach",
        region: "North Western Province",
        activities: ["All", "Beach", "Water Sports", "Nature"]
      },
      {
        id: 19,
        name: "Negombo",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/33/fd/17/negombo.jpg?w=1200&h=700&s=1",
        description: "A coastal town close to Colombo, famous for its lagoon, fishing industry, and sandy beaches.",
        rating: 4.4,
        price: 7000,
        category: "Beach",
        region: "Western Province",
        activities: ["All", "Beach", "Food", "Nature"]
      },
      {
        id: 20,
        name: "Adam's Peak (Sri Pada)",
        image: "https://images.squarespace-cdn.com/content/v1/5c94ab21a09a7e443410d831/1590078849853-IIGCWD8A82AFEGX72JSH/adam%27s+peak+climb+sri+lanka",
        description: "A sacred mountain revered by Buddhists, Hindus, Muslims, and Christians, famous for its sunrise trek.",
        rating: 4.9,
        price: 5000,
        category: "Spiritual",
        region: "Sabaragamuwa Province",
        activities: ["All", "Hiking", "Nature", "Culture"]
      },
      {
        id: 21,
        name: "Haputale",
        image: "https://www.lovesrilanka.org/wp-content/uploads/2020/06/LSL_B2_Blog_800x520-1.jpg",
        description: "A quaint hill town offering stunning views, lush tea plantations, and cool weather.",
        rating: 4.7,
        price: 8000,
        category: "Hill Station",
        region: "Uva Province",
        activities: ["All", "Hiking", "Nature", "Photography"]
      },
      {
        id: 22,
        name: "Kitulgala",
        image: "https://www.holidify.com/images/bgImages/KITULGALA.jpg",
        description: "An adventure hotspot famous for white-water rafting and lush rainforests.",
        rating: 4.6,
        price: 6000,
        category: "Adventure",
        region: "Sabaragamuwa Province",
        activities: ["All", "Hiking", "Water Sports", "Nature"]
      },
      {
        id: 23,
        name: "Pinnawala",
        image: "https://cdn.getyourguide.com/img/tour/3da49af2e758a626dd3dad1b7bf153c6f22d85558c2032bdf37760ccdd28a412.jpg/99.jpg",
        description: "Home to the famous Pinnawala Elephant Orphanage, where you can see elephants up close.",
        rating: 4.5,
        price: 5000,
        category: "Nature",
        region: "Sabaragamuwa Province",
        activities: ["All", "Nature", "Wildlife", "Culture"]
      },
      {
        id: 24,
        name: "Batticaloa",
        image: "https://i0.wp.com/srilankaislandtours.com/wp-content/uploads/2022/06/Matarah-Sri-Lanka-2.jpg?fit=612%2C408&ssl=1",
        description: "A coastal city known for its lagoons, beaches, and unique Tamil-Muslim culture.",
        rating: 4.4,
        price: 6500,
        category: "Beach",
        region: "Eastern Province",
        activities: ["All", "Beach", "Culture", "Water Sports"]
      },
      {
        id: 25,
        name: "Mannar",
        image: "https://static.wixstatic.com/media/017d2f_8c3092731a39483daa72f7dd51ff1272~mv2.jpg/v1/fill/w_1200,h_674,al_c,q_85/mannar.jpg",
        description: "A historically significant region known for its ancient baobab trees and pristine beaches.",
        rating: 4.3,
        price: 6000,
        category: "Historic Site",
        region: "Northern Province",
        activities: ["All", "Beach", "History", "Nature"]
      },
      {
        id: 26,
        name: "Matara",
        image: "https://us.lakpura.com/cdn/shop/files/LK951K0000-10-E.jpg?v=1724297912&width=3840",
        description: "A historic southern city with beautiful beaches, Dutch forts, and a lively culture.",
        rating: 4.6,
        price: 8000,
        category: "Beach",
        region: "Southern Province",
        activities: ["All", "Beach", "Culture", "History"]
      },
      {
        id: 27,
        name: "Ratnapura",
        image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/a9/ab/ca.jpg",
        description: "The 'City of Gems' famous for gem mining, lush greenery, and waterfalls.",
        rating: 4.5,
        price: 6500,
        category: "Nature",
        region: "Sabaragamuwa Province",
        activities: ["All", "Nature", "Hiking", "Culture"]
      },
      {
        id: 28,
        name: "Pasikuda",
        image: "https://s.joinup.lt/uploads/hotel/22046/gallery/original/Amaya-Beach-Passikudah-1.jpeg",
        description: "A tranquil beach destination with shallow waters, perfect for swimming and relaxing.",
        rating: 4.9,
        price: 12000,
        category: "Beach",
        region: "Eastern Province",
        activities: ["All", "Beach", "Snorkeling", "Water Sports"]
      },
      {
        id: 29,
        name: "Knuckles Mountain Range",
        image: "https://us.lakpura.com/cdn/shop/files/LK94009783-01-E.jpg?v=1653979666&width=3840",
        description: "A UNESCO World Heritage site offering scenic trekking routes and biodiversity.",
        rating: 4.8,
        price: 5000,
        category: "Adventure",
        region: "Central Province",
        activities: ["All", "Hiking", "Camping", "Nature"]
      },
      {
        id: 30,
        name: "Hambantota",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEX_QDKTAC8BNDkLUO3sZxxz1CCiw9udurLhzfPKcshw8pQtvQnlNrAkeHeu_YXJ2p-SM&usqp=CAU",
        description: "A developing coastal city known for its safari parks, beaches, and cultural landmarks.",
        rating: 4.3,
        price: 8500,
        category: "City",
        region: "Southern Province",
        activities: ["All", "Nature", "Beach", "Culture"]
      }
  ];  

  export default destination;